# Generated by Django 4.1.7 on 2023-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Pub', 'Published'), ('Drf', 'Draft')], max_length=3),
        ),
    ]
